# Site settings
title:          Dogyun Hwangbo
description:    "Dogyun Hwangbo's pages"
baseurl:        "/about"
url:            "https://dombegi.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:         
  name:         Dogyun Hwangbo
  url:          https://dombegi.github.io/
  email:        hwangbo.dogyun@gmail.com

# Build settings
markdown:       kramdown
kramdown:
   math_engine: mathjax
include:
  - _pages
# # For MathJax
# highlighter: rouge
# lsi: false
# excerpt_separator: "\n\n"
# incremental: false

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

remote_theme: chesterhow/tale

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-target-blank
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         

# Added by Dogyun 